installing terraform in runner

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -44,7 +44,19 @@ jobs:
 
       - name: Run Unit Tests
         run: make test
-      
+
+      - name: Check if Terraform is installed
+        id: check_terraform
+        run: |
+          if ! command -v terraform &> /dev/null; then
+            echo "Terraform not found. Installing..."
+            curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
+            echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
+            sudo apt update && sudo apt install -y terraform
+          else
+            echo "Terraform is already installed."
+          fi
+
       - name: Run terraform init
         run: make terraform-init
 
